# Generated by Django 4.1.3 on 2022-11-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='EmployeeName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
