# Generated by Django 4.1.3 on 2022-11-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0002_alter_employees_employeename'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='EmployeeFood',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
