# Generated by Django 4.1.3 on 2022-11-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0003_employees_employeefood'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='EmployeeFoodUrl',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
